export const comment = {
    uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
    author: 'qwe qwe',
    created_at: 1658494905635,
    text: 'йцййц',
    replies: 1,
    id: 'dJAGVjT6vjkma38cIeVB',
    discussion_id: null,
    disliked: [],
    liked: [],
    reply_id: null,
};

export const reply = {
    uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
    reply_id: 'dJAGVjT6vjkma38cIeVB',
    author: 'qwe qwe',
    discussion_id: 'dJAGVjT6vjkma38cIeVB',
    created_at: 1658498707165,
    text: 'ыыыы',
    id: 'FkpEEZiQTSzXIFILZrof',
    disliked: [],
    liked: [],
    replies: 0,
};

export const comments = [
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494898357,
        text: 'уц',
        id: 'E27ZtC2YCXb3rlHDWike',
        discussion_id: null,
        disliked: [],
        liked: [],
        replies: 0,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494899265,
        text: 'цц',
        disliked: [],
        id: 'B3cgWGoyaSroBi8zLNEF',
        liked: ['asdssqqwejajshczxmmjj1'],
        replies: 2,
        discussion_id: null,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494899740,
        text: '\n',
        disliked: ['kk1ja28i8djjhakk'],
        id: 'IYN2UHcjLHbwFGp2O3KJ',
        liked: [],
        discussion_id: null,
        replies: 0,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494900452,
        text: 'ц\n\nц',
        id: 'aFCqfCGiIusTtIBH2gUi',
        discussion_id: null,
        disliked: [],
        liked: [],
        replies: 0,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494901524,
        text: '\n\nцй',
        id: '53zmxpWMcaXMdQW8yEpD',
        discussion_id: null,
        disliked: [],
        liked: [],
        replies: 0,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494902570,
        text: 'йцйц',
        replies: 1,
        id: 'JCBCPYOArjPbNo0clbxT',
        discussion_id: null,
        disliked: [],
        liked: [],
        reply_id: null,
    },
    {
        uid: 'aezakmiaezakmiaezakmi',
        author: 'qwe qwe',
        created_at: 1658494903274,
        text: 'йц\n',
        id: 'oWqPoU45V4c7qZG3H2ce',
        replies: 3,
        disliked: ['SSSssaalkskasjdjmqwemqwejjasuc'],
        liked: [],
        discussion_id: null,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        author: 'qwe qwe',
        created_at: 1658494904349,
        text: 'йц',
        id: '1GjMfNNHG35kPhZ8R5XQ',
        discussion_id: null,
        disliked: [],
        liked: [],
        replies: 0,
        reply_id: null,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        reply_id: 'B3cgWGoyaSroBi8zLNEF',
        author: 'qwe qwe',
        discussion_id: 'B3cgWGoyaSroBi8zLNEF',
        created_at: 1658498710250,
        text: 'фффф',
        id: 'Oan44p9K9XFwnCsffzCS',
        disliked: [],
        liked: [],
        replies: 0,
    },
    {
        uid: 'aezakmiaezakmiaezakmi',
        reply_id: 'Oan44p9K9XFwnCsffzCS',
        author: 'qwe qwe',
        discussion_id: 'B3cgWGoyaSroBi8zLNEF',
        created_at: 1658498714478,
        text: 'фффф',
        id: 'lrreSLykpcFkWLwqoR5u',
        disliked: [],
        liked: [],
        replies: 0,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        reply_id: 'oWqPoU45V4c7qZG3H2ce',
        author: 'qwe qwe',
        discussion_id: 'oWqPoU45V4c7qZG3H2ce',
        created_at: 1658494908805,
        text: 'уйцу',
        id: 'BcTFIrc8QDnG2Y6wmXxy',
        disliked: [],
        liked: [],
        replies: 0,
    },
    {
        uid: 'aezakmiaezakmiaezakmi',
        reply_id: 'oWqPoU45V4c7qZG3H2ce',
        author: 'qwe qwe',
        discussion_id: 'oWqPoU45V4c7qZG3H2ce',
        created_at: 1658494911492,
        text: 'йцуйцу',
        id: 'FrjlZ1mFXHZczmKIYJ8y',
        disliked: [],
        liked: [],
        replies: 0,
    },
    {
        uid: 'q3TaIeyqSLEwdT1W1Mg6Cr9mHRoZ',
        reply_id: 'oWqPoU45V4c7qZG3H2ce',
        author: 'qwe qwe',
        discussion_id: 'oWqPoU45V4c7qZG3H2ce',
        created_at: 1658494913575,
        text: 'йцуйцу',
        id: 'iJubb0wcT1XmggN2hWM4',
        disliked: [],
        liked: [],
        replies: 0,
    },
];
